# $Id$

include $(TOPDIR)/.config
include $(TOPDIR)/$(ARCH).config

NAME	    = architeuthis
FORMAT	    = tar.bz2
VERSION	    = 0.2.1
STRIPPIT    = yes
DO_PREPARE  =
MAKEARGS    = release
FILES	    = /

include $(TOPDIR)/rules.mk
