# $Id: Makefile 276 2004-09-19 20:28:28Z gernot $

include $(TOPDIR)/.config
include $(TOPDIR)/$(SRCH).config

NAME	    = gocr
VERSION	    = 0.40
FORMAT	    = tar.gz
STRIPPIT    = yes
DO_PREPARE  = $(STAMP)-prepare
PREFIX	    = /usr
CFLAGS	    = $(CFLAGS_S)

FILES	    = /

include $(TOPDIR)/rules.mk
