# $Id$

include $(TOPDIR)/.config
include $(TOPDIR)/$(ARCH).config

NAME	    = pango
FORMAT	    = tar.bz2
VERSION	    = 1.28.1
STRIPPIT    = yes
DO_PREPARE  = $(STAMP)-prepare
ARGS        = --with-x=no
FILES	    = /

include $(TOPDIR)/rules.mk
