# $Id: Makefile 911 2007-02-15 22:34:15Z gernot $

include $(TOPDIR)/.config

NAME	    = ex
VERSION	    = 1.0.5
FORMAT	    = tar.gz
DO_PREPARE  = $(STAMP)-prepare
PREFIX	    = /opt/diet

FILES	    = ./opt/diet/lib-$(ARCH)/*.a
FILES	   += ./opt/diet/include

include $(TOPDIR)/rules.mk
