# $Id: Makefile 704 2006-08-09 22:08:34Z gernot $

include $(TOPDIR)/.config

VERSION	    = 0.3.6
NAME	    = libtasn1
FORMAT	    = tar.gz

DO_PREPARE  = $(STAMP)-prepare
PREFIX	    = /opt/diet

FILES	    = ./opt/diet/lib-$(ARCH)
FILES	   += ./opt/diet/include

include $(TOPDIR)/rules.mk
